### ISSUE TITLE
No module named 'md_utils'

### ISSUE THREAD

**Issue by muzammal0** [agentmorris/MegaDetector#117]
I am following your instruction on **https://github.com/agentmorris/MegaDetector/blob/main/api/synchronous/README.md** to implement **megadetector api** but once i start the docker image using "**sudo docker run -it -p 5050:1213 $API_DOCKER_IMAGE**" I get the following error :

File "/app/animal_detection_api/api_backend.py", line 19, in <module>
    from detection.run_detector import load_detector, convert_to_tf_coords
  File "/app/animal_detection_api/detection/run_detector.py", line 56, in <module>
    i**mport md_utils.path_utils as path_utils
ModuleNotFoundError: No module named 'md_utils'**
2023-10-10 06:37:08,842 INFO exited: detector (exit status 1; not expected)
2023-10-10 06:37:09,843 INFO gave up: detector entered FATAL state, too many start retries too quickly

**Comment by agentmorris** [comment]
Thank you for catching this!  There was some movement of files in the repo, and the Dockerfile had not been updated appropriately.  This has been fixed, please get the latest version of the repo and verify.  I'm 99.99% sure the issue has been addressed, and I verified on my end, so I am going to close the issue, but please re-open if you aren't able to verify the fix.

Out of curiosity... it's very rare that anyone wants to run MegaDetector via the synchronous API (99.99999% of MegaDetector use is via the standard inference path, even when hosted on a cloud platform), so I'm always interested in the scenario behind this.  If you're able to share anything about your use case, either here or via email to cameratraps@lila.science, I'd be interested in hearing what you're using the API for.

Thanks!
