### ISSUE TITLE
Specifying a relative path for the output json file

### ISSUE THREAD

**Issue by tomyamashita** [agentmorris/MegaDetector#137]
Hi Dan, 

I recently installed this version of Megadetector on a new computer and when I tried to specify a relative path for the output json file, it recognizes the file before going through the images but fails in saving the output file. 
![Screenshot 2024-07-02 134758](https://github.com/agentmorris/MegaDetector/assets/46978822/76c5b548-766f-409d-9d33-efd3b974a174)
![Screenshot 2024-07-02 134826](https://github.com/agentmorris/MegaDetector/assets/46978822/0e273c27-7542-4099-b9ce-f85999dc827c)

It does work when you specify an absolute path. 

Thanks, 
Tom

**Comment by agentmorris** [comment]
Thanks for catching this!  I was able to repro this.  It wasn't an issue with _all_ relative paths, it was an issue with a relative path with no folder component (e.g. "blah/detections.json" would have been fine, but "detections.json" was not).  Fixed now, so I'm closing the issue, but please verify and let me know if you aren't able to repro the fix.

Thanks for finding and reporting!
