### ISSUE TITLE
PackagesNotFoundError for mkl=2024.0*

### ISSUE THREAD

**Issue by nblumoe** [agentmorris/MegaDetector#147]
Thank you for providing MegaDetector!

I cannot successfully recreate a virtual environment from the included `environment-detector-mac.yml` env file due to the fixed mkl version not being available on the included channels.

I encountered the following issue when trying to use [EcoAssist](https://github.com/PetervanLunteren/EcoAssist) (https://github.com/PetervanLunteren/EcoAssist/issues/56), but I realised the source for this is in MegaDetector.

I verified it on the current `main` branch:

```
$ mamba env create --file envs/environment-detector-mac.yml
/usr/local/Caskroom/miniforge/base/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - conda-forge
 - pytorch
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl=2024.0*

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/pytorch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

The available versions are:
```
$ conda search mkl --channel conda-forge
Loading channels: done
# Name                       Version           Build  Channel
mkl                           2019.5             281  conda-forge
mkl                           2020.0             166  conda-forge
mkl                           2020.1             216  conda-forge
mkl                           2020.1             218  conda-forge
mkl                           2020.2             260  conda-forge
mkl                           2020.2    h694c41f_260  conda-forge
mkl                           2020.4    h08c4f10_301  conda-forge
mkl                         2021.1.1     h08c4f10_69  conda-forge
mkl                         2021.2.0    h08c4f10_389  conda-forge
mkl                         2021.3.0    h08c4f10_555  conda-forge
mkl                         2021.4.0    h89fa619_689  conda-forge
mkl                         2022.0.0    h89fa619_782  conda-forge
mkl                         2022.1.0    h860c996_928  conda-forge
mkl                         2022.2.1  h44ed08c_16951  conda-forge
mkl                         2022.2.1  h44ed08c_16952  conda-forge
mkl                         2023.0.0  h44ed08c_25369  conda-forge
mkl                         2023.0.0  h44ed08c_31031  conda-forge
mkl                         2023.1.0  h44ed08c_43546  conda-forge
mkl                         2023.1.0  h44ed08c_48681  conda-forge
mkl                         2023.2.0  h54c2260_50500  conda-forge
mkl                         2023.2.0     hfe8bc8c_34  conda-forge
mkl                         2023.2.0     hfe8bc8c_35  conda-forge
mkl                         2023.2.0     hfe8bc8c_36  conda-forge
mkl                         2023.2.0     hfe8bc8c_37  conda-forge
mkl                         2023.2.0     hfe8bc8c_38  conda-forge
mkl                         2023.2.0  hfe8bc8c_49505  conda-forge
mkl                         2023.2.0  hfe8bc8c_49506  conda-forge
mkl                         2023.2.0  hfe8bc8c_49578  conda-forge
mkl                         2023.2.0  hfe8bc8c_50499  conda-forge
```

I could use one of the 2023 versions and did so for EcoAssist, but I'm not sure about the compatibility implications and it would be great to have the env file fixed instead.

I'd be happy to provide a PR as well to use the latest 2023 version instead if that is desired.
Thank you!

**Comment by agentmorris** [comment]
Thanks for reporting this!  Indeed, it appears that the 2024.0.0 build was removed recently, I have no idea why, and can't find any explanation online.  I would like to fix this, but I don't have access to an Intel Mac to test on... ironically I just replaced an Intel Mac with an Apple silicon Mac and was excited that I would no longer have to use AWS VMs to test compatibility issues, and yet here we are. :)

A couple requests for @nblumoe...

1. Can you run "conda info" and post the results here?  You can remove any directory names that you don't want to post, I mostly want to see the architecture platform strings so I can search for packages that are available in your environment.
2. Yes, I think that installing an older version will be fine; this environment file is using a PyTorch version from ~2021, so there should be no compatibility issues with mkl versions from 2022/2023.  My inclination is to change it in the env file to "mkl<2024.0".  Can you try that?  If that runs without issue and gives reasonable-looking results, I'll be 98% sure we're in the clear.  But if we get that far and we really want to triple-check that there are no hidden numerical issues, I can provide more instructions about running the suite of regression tests in [md_tests.py](https://github.com/agentmorris/MegaDetector/blob/main/megadetector/utils/md_tests.py).

If that doesn't get us to a solution, I will try to repro this on an Intel Mac VM.

Thanks again for reporting this!

**Comment by nblumoe** [comment]
Great, happy to help.

Here is the condo info:

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/foo/.condarc
 populated config files : /Users/foo/.condarc
          conda version : 23.10.0
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=skylake
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/foo/miniconda3  (writable)
      conda av data dir : /Users/foo/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/foo/miniconda3/pkgs
                          /Users/foo/.conda/pkgs
       envs directories : /Users/foo/miniconda3/envs
                          /Users/nblu/.conda/envs
               platform : osx-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.5 Darwin/24.1.0 OSX/10.16 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

I'll look into the dependency downgrade and tests next. I had only used MegaDetector via EcoAssist previously, but this is a good opportunity for getting used to MegaDetector. I'll report back on it here.
