### ISSUE TITLE
MD output consistent for `--keep_extracted_frames`

### ISSUE THREAD

**Issue by PetervanLunteren** [agentmorris/MegaDetector#153]
EcoAssist reads every line of MD output, and extracts the useful information to show in the progress window. The MD output is slightly different when using different settings (i.e., when keeping the frames). See the cases below.

#### MD output without `--frame_folder` and `--keep_extracted_frames`
```bash
(ecoassistcondaenv-base) peter@Peters-MacBook-Pro-2 ~ % '/Applications/.EcoAssist_files/miniforge/envs/ecoassistcondaenv-base/bin//python' '/Applications/.EcoAssist_files/cameratraps/megadetector/detection/process_video.py' '--json_confidence_threshold=0.01' '--recursive' '--time_sample=1' '--max_width=1280' '--quality=85' '--output_json_file=/Users/peter/Downloads/test-imgs-vids/imgs_and_vids/video_recognition_file.json' '/Applications/.EcoAssist_files/models/det/MegaDetector 5a/[md_v5a.0.0.pt](http://md_v5a.0.0.pt/)' '/Users/peter/Downloads/test-imgs-vids/imgs_and_vids'

Imported YOLOv5 as utils.*
Using PyTorch version 1.13.1
Fusing layers...
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Sending model to GPU
Loaded model in 2.02 seconds
Found 12 videos in folder /Users/peter/Downloads/test-imgs-vids/imgs_and_vids
100%|███████████████████████████████████████████| 12/12 [00:48<00:00,  4.00s/it]
Output file saved at /Users/peter/Downloads/test-imgs-vids/imgs_and_vids/video_recognition_file.frames.json
Converting frame-level results to video-level results
100%|█████████████████████████████████████| 168/168 [00:00<00:00, 370864.77it/s]
Found 12 unique videos in 168 frame-level results
100%|████████████████████████████████████████| 12/12 [00:00<00:00, 96052.76it/s]
```

#### MD output with `--frame_folder` and `--keep_extracted_frames`
```bash
(ecoassistcondaenv-base) peter@Peters-MacBook-Pro-2 ~ % '/Applications/.EcoAssist_files/miniforge/envs/ecoassistcondaenv-base/bin//python' '/Applications/.EcoAssist_files/cameratraps/megadetector/detection/process_video.py' '--json_confidence_threshold=0.01' '--frame_folder=/var/folders/qk/bfzt2l5j6pjbshttpt92qw0c0000gn/T/tmpxm5ghawr' '--keep_extracted_frames' '--recursive' '--time_sample=1' '--max_width=1280' '--quality=85' '--output_json_file=/Users/peter/Downloads/test-imgs-vids/imgs_and_vids/video_recognition_file.json' '/Applications/.EcoAssist_files/models/det/MegaDetector 5a/[md_v5a.0.0.pt](http://md_v5a.0.0.pt/)' '/Users/peter/Downloads/test-imgs-vids/imgs_and_vids'

100%|███████████████████████████████████████████| 12/12 [00:19<00:00,  1.62s/it]
Extracted frames for 12 videos
Running MegaDetector
PyTorch reports 0 available CUDA devices
PyTorch reports Metal Performance Shaders are available
GPU available: True
Imported YOLOv5 as utils.*
Using PyTorch version 1.13.1
Fusing layers...
Model summary: 574 layers, 139990096 parameters, 0 gradients, 207.9 GFLOPs
Sending model to GPU
Loaded model in 1.73 seconds
Loaded model in 1.73 seconds
100%|█████████████████████████████████████████| 168/168 [00:33<00:00,  5.01it/s]
Output file saved at /Users/peter/Downloads/test-imgs-vids/imgs_and_vids/video_recognition_file.frames.json
Converting frame-level results to video-level results
100%|█████████████████████████████████████| 168/168 [00:00<00:00, 375009.62it/s]
Found 12 unique videos in 168 frame-level results
100%|████████████████████████████████████████| 12/12 [00:00<00:00, 97541.95it/s]
```

When the user specified to run a species classifier over the frames, EcoAssist has to save the frames in a temp folder. Which results in a different MD process, and a different output. The EcoAssist progressbars therefore behave inconsistent. I could of course change the EcoAssist code (if `--keep_extracted_frames` in command: etc), but I though it would be easiest to fix at the source.

Would it be possible to:
* In the case of running MD without `--frame_folder` and `--keep_extracted_frames`, would it be possible to have the pbar increase per frame instead of per video? If not, no worries. I'll then adjust the EcoAssist backend and report per-video-progress. Also, EcoAssist checks for the line 'GPU available: True' or 'GPU available: False'. That is why the window shows 'Running on: Unknown'. Could you add this to the output?
* In the case of running MD with `--frame_folder` and `--keep_extracted_frames`, would it be possible to have MD output "Extracting frames..." or something similar prior to the first pbar? EcoAssist then knows what the pbar is for.

Thanks!

**Comment by agentmorris** [comment]
> In the case of running MD without --frame_folder and --keep_extracted_frames, would it be possible to have the pbar increase per frame instead of per video?

This would be tricky; it doesn't know the total number of frames a priori.  Can you use the percentage in both cases?


> Also, EcoAssist checks for the line 'GPU available: True' or 'GPU available: False'. That is why the window shows 'Running on: Unknown'. Could you add this to the output?

Done.


> In the case of running MD with --frame_folder and --keep_extracted_frames, would it be possible to have MD output "Extracting frames..." or something similar prior to the first pbar? EcoAssist then knows what the pbar is for.

I'm 99% sure that if you add --verbose to the command line, you'll get a printout in the place you want it.  Confirm?

--

More generally, though, it makes me _slightly_ nervous that something as important as EcoAssist is taking dependencies on the exact command line output of any scripts in the MD repo; I don't think of the command-line output as guaranteed to be stable over time.  It's not that I'm changing it willy-nilly, but I do sometimes, e.g., remove printouts when they no longer seem useful.  Also in a multi-threaded world, you can't really guarantee that lines won't get broken in funny ways.

I don't think we want to do anything about this now, but some time next year we should probably agree on exactly what indicators you want, and find a stable, persistent way to get there, either by just informally marking some debug output as important in comments in the code, or by moving some things to, e.g., a dedicated log meant to send information to EcoAssist.

In general, for now, I would use --verbose whenever it's available, and I wouldn't depend on command-line output for anything that will hang the GUI (e.g. don't block the UI waiting for the "thanks for MegaDetect'ing" line, just in case).  But as long as it's for relatively non-critical things like progress bars, this approach is OK for now.

Thanks for all the hard work the last few weeks on video support!

**Comment by PetervanLunteren** [comment]
Thanks! That works :) 

It would indeed be a good idea to figure something out regarding the information transfer from MD to EcoAssist (like pbar info). It does feel very hacky to read the output lines...
